Geo data frames
IBM/nzpyida pull request #76
Opened 2023-07-19 16:21 UTC by mrozpawel

```
============================================================= test session starts ==============================================================
platform darwin -- Python 3.11.3, pytest-7.3.1, pluggy-1.0.0
rootdir: /Users/pawelmrz/Documents/persistent/nzpyida
plugins: flaky-3.7.0, anyio-3.6.2
collected 479 items                                                                                                                            

test_aggregation.py .................................                                                                                    [  6%]
test_association_rules.py .........                                                                                                      [  8%]
test_base.py .....s........ss..............                                                                                              [ 15%]
test_base_connexion.py ............                                                                                                      [ 17%]
test_base_private.py ......................                                                                                              [ 22%]
test_base_table_manipulation.py ..s..sss..................                                                                               [ 27%]
test_feature_selection.py ssssssssssss..........................................                                                         [ 38%]
test_filtering.py ..........                                                                                                             [ 40%]
test_frame.py ....................................................................s....                                                  [ 56%]
test_frame_connexion.py ......                                                                                                           [ 57%]
test_frame_private.py ........................                                                                                           [ 62%]
test_geoFrame.py ...........................                                                                                             [ 68%]
test_geoSeries.py .......sss......s.s................s....                                                                               [ 76%]
test_indexing.py .....................                                                                                                   [ 80%]
test_internals.py .....                                                                                                                  [ 81%]
test_kmeans.py .........                                                                                                                 [ 83%]
test_naive_bayes.py .........                                                                                                            [ 85%]
test_series.py ...                                                                                                                       [ 86%]
test_sorting.py ............                                                                                                             [ 88%]
test_statistics.py ................................................                                                                      [ 98%]
test_utils.py ......                                                                                                                     [100%]
=========================================== 453 passed, 26 skipped, 17 warnings in 895.00s (0:14:55) ===========================================
```

2023-07-19 16:22 UTC, mrozpawel commented
Fix for #53

2023-07-21 10:26 UTC, mplpl requested changes
We need to also modify MANIFEST.in file and remove global-exclude from it - otherwise getFrame and geoSeries will not be included in whl file after build.

2023-07-21 10:26 UTC, mplpl commented on nzpyida/__init__.py
>  		   'base', 'exceptions', 'filtering', 'frame', 'indexing',
also add geoFrame and geoSeries here

2023-07-21 10:27 UTC, mplpl commented
Can we also rename geoFrame.py to geo_frame.py and geoSeries.py to geo_series.py

2023-07-21 10:32 UTC, mplpl commented on docs/source/geospatial.rst
> +Assuming that you've got connection to the databased established via IdaDataBase object named 'idadb'.
Above this sentence, it talks about ODBC and JDBC - let's add nzpy there as well (and make it first option)

2023-07-21 14:39 UTC, mplpl approved these changes

2023-07-21 14:40 UTC, merged